### ISSUE TITLE
 Visualization

### ISSUE THREAD

**Issue by ClockworkShelley** [geekyutao/RN#1]
Hi,geekyutao. I am very interested in your image inpainting work, the idea of Region Normalization is amazing. I notice that you visualized certain features of the inpainting network in your paper, I am very curious about this process. Could you share the code of this part, my email:1298647580@qq.com
thank you very much.

**Comment by geekyutao** [comment]
Hi, there,
	The visualization is actually very simple. You can follow these:

	Attn = mean(sample_features, 0)
	cv2.applyColorMap(attn, cv2.COLORMAP_JET)

Best,
Tao
发件人: ClockworkShelley
发送时间: 2020年2月29日 20:17
收件人: geekyutao/RN
抄送: Subscribed
主题: [geekyutao/RN] Visualization (#1)

Hi,geekyutao. I am very interested in your image inpainting work, the idea of Region Normalization is amazing. I notice that you visualized certain features of the inpainting network in your paper, I am very curious about this process. Could you share the code of this part, my email:1298647580@qq.com
thank you very much.
