### ISSUE TITLE
about demo code

### ISSUE THREAD

**Issue by mychina75** [geekyutao/RN#10]
Hi, thank you for your work.
Do not find codes to test a image with mask file using the pretrained model.
It will be helpful if you can provide a sample version to do it.
:)

**Comment by geekyutao** [comment]
Hi, please read the eval.py

**Comment by geekyutao** [comment]
> Hi, thank you for your work.
> Do not find codes to test a image with mask file using the pretrained model.
> It will be helpful if you can provide a sample version to do it.
> :)

Hi, please read the eval.py

**Comment by mychina75** [comment]
Thank you.  It works. 
cmd like:
python eval --bs=1 --img_flist=img.lst --mask_flist=mask.lst --model=pretrained_model/x_admin.cluster.localRN-0.8RN-Net_bs_14_epoch_3.pth --save=True --save_path=./test_results

The inpainted image has color difference issue. 
Reason maybe the model was not full trained?

**Comment by geekyutao** [comment]
> Thank you. It works.
> cmd like:
> python eval --bs=1 --img_flist=img.lst --mask_flist=mask.lst --model=pretrained_model/x_admin.cluster.localRN-0.8RN-Net_bs_14_epoch_3.pth --save=True --save_path=./test_results
> 
> The inpainted image has color difference issue.
> Reason maybe the model was not full trained?

I don't have this issue in my implementation. The model was full trained on Places2. Maybe you can show some examples.

**Comment by mychina75** [comment]
please check the test images. thank you.
[test.zip](https://github.com/geekyutao/RN/files/4750691/test.zip)

**Comment by geekyutao** [comment]
> please check the test images. thank you.
> [test.zip](https://github.com/geekyutao/RN/files/4750691/test.zip)

It's wired. I never encounter this before. Make sure your mask is correct (binary: 0 for background, 255 for hole). I don't know if you have some modification to the codes. Please check out it. I'm very sure the "eval.py" has no problem.

**Comment by mychina75** [comment]
I changed image save function from skimage.io.imsave to scipy.misc.imsave. because in my python env, import skimage.io always failed. I am not sure if this is the reason.

the input images are attached here. 
[test_input.zip](https://github.com/geekyutao/RN/files/4750890/test_input.zip)

**Comment by geekyutao** [comment]
> I changed image save function from skimage.io.imsave to scipy.misc.imsave. because in my python env, import skimage.io always failed. I am not sure if this is the reason.
> 
> the input images are attached here.
> [test_input.zip](https://github.com/geekyutao/RN/files/4750890/test_input.zip)

QAQ... Must be this!

**Comment by mychina75** [comment]
I change back the code but result is similiar.
maybe VGG loss should add for training? VGG loss can always work, in my opinion.
