### ISSUE TITLE
How to construct evaluating image-mask pairs?

### ISSUE THREAD

**Issue by junleen** [geekyutao/RN#13]
Hi, Yu, thank you for sharing your code. 
I have a simple question, that is how to construct testing cases. For example, the number of images in validation data of Places2 is 36500, but the number of masks is 12000. In the code of `dataset.py`, we take the index-th image from image set(0~36499), while you just take the index-th mask in `self.mask_data` in testing model of **Dataset** class. This will incur some errors when loading masks and then return the first image sample. 
```python
try:
    item = self.load_item(index)
except:
    print('loading error: ' + self.data[index])
    item = self.load_item(0)
```
With such code, you will only test 12000 images from Places2. Am I right?

Hoping for your reply!

**Comment by geekyutao** [comment]
> Hi, Yu, thank you for sharing your code.
> I have a simple question, that is how to construct testing cases. For example, the number of images in validation data of Places2 is 36500, but the number of masks is 12000. In the code of `dataset.py`, we take the index-th image from image set(0~36499), while you just take the index-th mask in `self.mask_data` in testing model of **Dataset** class. This will incur some errors when loading masks and then return the first image sample.
> 
> ```python
> try:
>     item = self.load_item(index)
> except:
>     print('loading error: ' + self.data[index])
>     item = self.load_item(0)
> ```
> 
> With such code, you will only test 12000 images from Places2. Am I right?
> 
> Hoping for your reply!


Hi. Thanks for your interest! I repeat the 12k masks about 3 times to get 36k masks. Please make sure that the number of test images equals to the number of masks before running eval.py.
