### ISSUE TITLE
自己训练的模型

### ISSUE THREAD

**Issue by ZHANG-hengzhi** [geekyutao/RN#14]
你好，我想问一下，我自己训练模型之后进程测试KeyError: 'discriminator.module.conv1.0.weight_orig' 报这个错，是要进行好几步训练吗。

**Comment by ZHANG-hengzhi** [comment]
训练的步骤应该什么样的呀，非常感谢

**Comment by geekyutao** [comment]
> 你好，我想问一下，我自己训练模型之后进程测试KeyError: 'discriminator.module.conv1.0.weight_orig' 报这个错，是要进行好几步训练吗。

Hi Hengzhi! We discussed this in email. You can just follow my suggestion in it. Thanks!

**Comment by ZHANG-hengzhi** [comment]
大神，我就是在main文件里配置了一下变量，现在改成用CPU可以进行测试了。我还想了解一下RN作为一种即插即用模块，我在用的时候有什么注意事项吗，因为刚开始研究inpainting，想着创新点可以借用这个模块，但是在之前没有相关的改网络结构的经历，望大神指点。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "geekyutao"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 上午10:06
收件人: "geekyutao/RN"<RN@noreply.github.com&gt;; 
抄送: "张恒志"<594300065@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [geekyutao/RN] 自己训练的模型 (#14)





  
你好，我想问一下，我自己训练模型之后进程测试KeyError: 'discriminator.module.conv1.0.weight_orig' 报这个错，是要进行好几步训练吗。
  
Hi Hengzhi! We discussed this in email. You can just follow my suggestion in it. Thanks!
