### ISSUE TITLE
question

### ISSUE THREAD

**Issue by weizitai** [geekyutao/RN#18]
Can you tell me how many epochs you have iterated on the three data sets?

**Comment by geekyutao** [comment]
Hi, I would train RN at least 2 epochs for Places2 and 10 epochs for CelebA and longer training may bring better results.

**Comment by geekyutao** [comment]
> Can you tell me how many epochs you have iterated on the three data sets?

Hi, I would train RN at least 2 epochs for Places2 and 10 epochs for CelebA and longer training may bring better results.
