### ISSUE TITLE
some difficult

### ISSUE THREAD

**Issue by D-YL** [geekyutao/RN#2]
Hello, geekyutao:
I'm interseted in your work and want to try it, but i have some problems.
I would be appreciated if you could share the the fitted model that I can use it to generate a good result instead of training the net again.
Does the words you said in Preparation mean that we should prepare the image and mask ourselves?
Are masks required for successful inpainting,Does this mean the inverse operation only works for masks applied to the image? Doesn't this reduce the potential for real-world application?
I apologize for any misunderstanding, thankyou.

**Comment by geekyutao** [comment]
Hi, there:
    Thanks! I am glad you are insterested in RN. The pretrained model has already been uploaded. Hope it helps! The Preparation means to prepare the file lists of training data and mask, which you can also see in EdgeConnect repository. Masks are required. Real-world images may have no masks while they are convinient to get through mask detection technique. 

Cheer,
Tao

**Comment by juechen-zzz** [comment]
Hi, when I use your method to train my own data. There are some problems.
When I run the eval.py:
`Traceback (most recent call last):
 File "eval.py", line 232, in <module>
 eval()
 File "eval.py", line 73, in eval
 prediction = prediction * mask + gt * (1 - mask)'
'RuntimeError: The size of tensor a (664) must match the size of tensor b (667) at non-singleton dimension 2`

I check the code, find that 
`        with torch.no_grad():
            prediction = model.generator(gt, mask)'
            prediction = prediction * mask + gt * (1 - mask)

gt.shape =torch.Size([1, 3, 667, 1000]),
mask.shape = torch.Size([1, 1, 667, 1000])
however, prediction.shape = torch.Size([1, 3, 664, 1000])

Can you help me fix the problem? Thank you!

**Comment by geekyutao** [comment]
> Hi, when I use your method to train my own data. There are some problems.
> When I run the eval.py:
> `Traceback (most recent call last): File "eval.py", line 232, in <module> eval() File "eval.py", line 73, in eval prediction = prediction * mask + gt * (1 - mask)' 'RuntimeError: The size of tensor a (664) must match the size of tensor b (667) at non-singleton dimension 2`
> 
> I check the code, find that
> ` with torch.no_grad():
> prediction = model.generator(gt, mask)'
> prediction = prediction * mask + gt * (1 - mask)
> 
> gt.shape =torch.Size([1, 3, 667, 1000]),
> mask.shape = torch.Size([1, 1, 667, 1000])
> however, prediction.shape = torch.Size([1, 3, 664, 1000])
> 
> Can you help me fix the problem? Thank you!

Hi, how about input a square image like [667,667] ?
