### ISSUE TITLE
Question about losses

### ISSUE THREAD

**Issue by hhheeexxxuuu** [geekyutao/RN#22]
Hello, I don not find style and perceptual losses in your code which paly a important role in results. Can you give me some suggestions?

**Comment by geekyutao** [comment]
> Hello, I don not find style and perceptual losses in your code which paly a important role in results. Can you give me some suggestions?

Hi, we found the style and perceptual losses are not that efficient so that we removed them in this version.

**Comment by hhheeexxxuuu** [comment]
Ok, thank you!
