### ISSUE TITLE
about channels

### ISSUE THREAD

**Issue by crazygirl1992** [geekyutao/RN#23]
the encoder part,the input mask have 3 channels but the feature have 64 channels,the code put x*label, it's error?

**Comment by geekyutao** [comment]
> the encoder part,the input mask have 3 channels but the feature have 64 channels,the code put x*label, it's error?

The input mask after prepocessing is 1 channel. And I also expand the mask channel in RN-L for the inconsistency.
https://github.com/geekyutao/RN/blob/master/rn.py#L126
