### ISSUE TITLE
Why use the given pre-training model to get such results？

### ISSUE THREAD

**Issue by shangcai1** [geekyutao/RN#24]
![image](https://user-images.githubusercontent.com/49365454/108815350-46c6cf80-75ef-11eb-854f-9fc5f4e1c090.png)

**Comment by geekyutao** [comment]
Seems like incorrect merging. Pls make sure of the mask is correctly input. https://github.com/geekyutao/RN/blob/master/dataset.py#L82

**Comment by shangcai1** [comment]
Thank you for your reply, but I did not find the problems











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geekyutao/RN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 下午4:02
收件人:&nbsp;"geekyutao/RN"<RN@noreply.github.com&gt;;
抄送:&nbsp;"财务室 安于心"<1147626517@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [geekyutao/RN] Why use the given pre-training model to get such results？ (#24)





 
Seems like incorrect merging. Pls make sure of the mask is correctly input. https://github.com/geekyutao/RN/blob/master/dataset.py#L82
