### ISSUE TITLE
Training on custom dataset with custom mask for Inpainting

### ISSUE THREAD

**Issue by Akshay-Ijantkar** [geekyutao/RN#25]
Hello @geekyutao 
Great work on the paper and even the results look amazing!

Can you please guide me with step by step process on how we need to prepare a dataset for a custom image dataset with a custom mask (if possible)?

How the masks will look like in the sense that whether it will be a colour image on which white patches (the part that will be inpainted from the model) is drawn or it will be a completely black image on which white patches (the part that will be inpainted from the model) is drawn? (in short how to prepare mask and then how to supply it for model training)

I referred to your steps but couldn't completely follow them.
Thank you in advance!

**Comment by geekyutao** [comment]
> Hello @geekyutao
> Great work on the paper and even the results look amazing!
> 
> Can you please guide me with step by step process on how we need to prepare a dataset for a custom image dataset with a custom mask (if possible)?
> 
> How the masks will look like in the sense that whether it will be a colour image on which white patches (the part that will be inpainted from the model) is drawn or it will be a completely black image on which white patches (the part that will be inpainted from the model) is drawn? (in short how to prepare mask and then how to supply it for model training)
> 
> I referred to your steps but couldn't completely follow them.
> Thank you in advance!

Thanks! I will make a more detailed instruction once I have time.
