### ISSUE TITLE
I have trained this on single gpu with cuda 11.2 and pytorch 1.8 but still confuse about multi-gpu training

### ISSUE THREAD

**Issue by sanicle** [geekyutao/RN#27]
how can i use multi-gpu pretrained model on single gpu. this code seems not work.
btw, i have sent mail to yutao about license of this great work (alexliu@demotree.vip) expect to get a reply :)

**Comment by geekyutao** [comment]
> how can i use multi-gpu pretrained model on single gpu. this code seems not work.
> btw, i have sent mail to yutao about license of this great work ([alexliu@demotree.vip](mailto:alexliu@demotree.vip)) expect to get a reply :)

Hi, pls modify https://github.com/geekyutao/RN/blob/master/main.py#L237 from if opt.gpus > 1: to if opt.gpus >= 1.
