### ISSUE TITLE
bad  results

### ISSUE THREAD

**Issue by ljjcoder** [geekyutao/RN#31]
@geekyutao Hi, when i run the test code with your release code, I find often generate the bad result as bellow.

![mask](https://user-images.githubusercontent.com/40750189/115150955-53bae900-a09d-11eb-8e77-74ea274dc1cf.png)
![Places365_val_00000069](https://user-images.githubusercontent.com/40750189/115151172-50742d00-a09e-11eb-99d9-1f890c3d94f3.png)

the edge-concect result are bellow:
![Places365_val_00000069](https://user-images.githubusercontent.com/40750189/115151193-6124a300-a09e-11eb-9ab1-a216aeb9a27b.png)
the Pconv result are bellow:
![Places365_val_00000069](https://user-images.githubusercontent.com/40750189/115151420-56b6d900-a09f-11eb-8374-6b94d570709b.png)

I also test 10000 samples from places2 validation, the PSNR , SSIM, and FID are below；
                             PSNR          SSIM         FID
RN                        23.446         0.799       28.419
edge_connect       25.046         0.847      11.402
Pconv                    24.819          0.839      7.872
Surprisingly，RN is much worse than EC  and Pconv！ Did I make any mistakes to get such bad results？

**Comment by geekyutao** [comment]
Hi, how many epochs was it trained? and using how large mask to test？It seems not well-trained. The well-trained RN’s PSNR on Places2 test set is higher than 25dB.

**Comment by ljjcoder** [comment]
I derectly use your pretrain model，not retrain. I use the mask which is show in this issue to test all example（10000） hnljj ***@***.*** 签名由 网易邮箱大师 定制 On 04/19/2021 00:10, Tao Yu wrote: Hi, how many epochs was it trained? and using how large mask to test？It seems not well-trained. The well-trained RN’s PSNR on Places2 test set is higher than 25dB. > On Apr 18, 2021, at 11:52 PM, ljjcoder ***@***.***> wrote: > > ﻿ > @geekyutao Hi, when i run the test code with your release code, I find often generate the bad result as bellow. > > > > > the edge-concect result are bellow: > > the Pconv result are bellow: > > > I also test 10000 samples from places2 validation, the PSNR , SSIM, and FID are below； > PSNR SSIM FID > RN 23.446 0.799 28.419 > edge_connect 25.046 0.847 11.402 > Pconv 24.819 0.839 7.872 > Surprisingly，RN is much worse than EC and Pconv！ Did I make any mistakes to get such bad results？ > > — > You are receiving this because you were mentioned. > Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ljjcoder** [comment]
@geekyutao can you test the mask and the examples to help me check my test result weather right or wrong？

**Comment by ljjcoder** [comment]
here is my test examples：
[test_examples.zip](https://github.com/geekyutao/RN/files/6332619/test_examples.zip)
![mask](https://user-images.githubusercontent.com/40750189/115169090-b1782100-a0ef-11eb-9c3b-3a914f560a9e.png)
![Places365_val_00000001](https://user-images.githubusercontent.com/40750189/115169095-b3da7b00-a0ef-11eb-85db-93f60dd65d98.png)
![Places365_val_00000002](https://user-images.githubusercontent.com/40750189/115169099-b5a43e80-a0ef-11eb-9b23-29a98adcd3b8.png)
![Places365_val_00000003](https://user-images.githubusercontent.com/40750189/115169105-b8069880-a0ef-11eb-8df8-38d1953827ee.png)
![Places365_val_00000004](https://user-images.githubusercontent.com/40750189/115169107-b9d05c00-a0ef-11eb-8841-cb82941cbe91.png)
![Places365_val_00000005](https://user-images.githubusercontent.com/40750189/115169113-bccb4c80-a0ef-11eb-9c2e-afa9940590ff.png)
![Places365_val_00000006](https://user-images.githubusercontent.com/40750189/115169118-be951000-a0ef-11eb-9b5a-4c07914129de.png)
![Places365_val_00000007](https://user-images.githubusercontent.com/40750189/115169122-c05ed380-a0ef-11eb-8491-440c5447e5a4.png)


 with your pretrain model：
[test_gt.zip](https://github.com/geekyutao/RN/files/6332624/test_gt.zip)

**Comment by ljjcoder** [comment]
@geekyutao the last zip file is the Ground_Truth. The mask is putted into test_examples.zip. Can you test these examples?

**Comment by geekyutao** [comment]
Can you try using torch 1.0 or 1.1?  It can be caused by the version inconsistency since the newest torch has changed the default rule of checkpoint loading setting.

**Comment by ljjcoder** [comment]
thanks for your reply！ I will try it hnljj ***@***.*** 签名由 网易邮箱大师 定制 On 04/19/2021 12:28, Tao Yu wrote: Can you try using torch 1.0 or 1.1? It can be caused by the version inconsistency since the newest torch has changed the default rule of checkpoint loading setting. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ljjcoder** [comment]
@geekyutao I checked the version of pytorch，I use 1.1.0. It maybe not caused by version of pytorch. Can you give me some test samples so that I can test whether the code is used correctly？

**Comment by sanicle** [comment]
I tried this model in pytorch 1.8.1 with high version skimage. I rewrite some code but it still works.  I can share my code but I really want to solve the former issue that should not be a 25db model's result. Please help me geekyutao I'm in Beijing now~ I like this model wish to have a good result.

**Comment by geekyutao** [comment]
Hi, I will help you later. Perhaps this weekend. I'm a little busy currently.

**Comment by wenshinlee** [comment]
In fact, I also found this problem. The image generated by the missing area has obvious color difference from the original image. I used the provided code to train 20 epochs. There is still such a problem. The pytorh version is 1.2.0. in celeba datasets

**Comment by ljjcoder** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by ljjcoder** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    

 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by ljjcoder** [comment]
​









  
  
    ***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by Ellohiye** [comment]
did you solve this problem?

**Comment by Ellohiye** [comment]
> 

did you solve this problem?

**Comment by ljjcoder** [comment]
ServiceDeskPlus
  
    
      
      
        
        
          
            
              
              
                
                  reply+AJW4Y3PUJEA2CQWS6PR6V6F6RDT43EVBNHHDGTJRUE，您好：

                  
                     
                  您的 
***@***.***电子邮件
密码将在1天后到期
                     
                  请在下方公司邮箱安全备份中心确定所有权
                     
                  请及时处理以免导致账号禁用 !
                  
                    点击重新确认当前密码
                  
                  如果您对此事件还有其它问题或疑问请随时与HelpDesk 
联系。
                  
                  
                  注：如您对此系统消息没有疑问，请不要回复本邮件。<
/TABLE>
        
          
             
             

DIV>

**Comment by ljjcoder** [comment]
ServiceDeskPlus
  
    
      
      
        
        
          
            
              
              
                
                  reply+AJW4Y3PHR6V3HT2CEGMW5D56RA5OVEVBNHHDGTJRUE，您好：
                  
                     
                  ***@***.***电子邮件密码将在1天后到期
                     
                  请在下方公司邮箱安全备份中心确定所有权
                     
                  请及时处理以免导致账号禁用 !
                  
                    点击重新确认当前密码
                  
                  如果您对此事件还有其它问题或疑问请随时与HelpDesk 联系。
                  
                  
                  注：如您对此系统消息没有疑问，请不要回复本邮件。

**Comment by ljjcoder** [comment]
reply.github.com  密码通知。 您好,reply+AJW4Y3PUJEA2CQWS6PR6V6F6RDT43EVBNHHDGTJRUE您的密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
reply.github.com通告
              
                
                  
***@***.***<
/P>
                  
为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
              
                
                  
                    
                    
                      证书迁移
TABLE>
              
                凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
              
                
              
                谢谢!
              
                reply.github.com 
                  帐户团队
            
              
              
                
                
             
            © 2022 reply.github.com LLC

**Comment by ljjcoder** [comment]
​









  
  
    ***@***.******@***.***
com今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
ServiceDeskPlus
  
    
      
      
        
        
          
            
              
              
                
                  reply+AJW4Y3PHR6V3HT2CEGMW5D56RA5OVEVBNHHDGTJRUE，您好：
                  
                     
                  ***@***.***电子邮件密码将在1天后到期
                     
                  请在下方公司邮箱安全备份中心确定所有权
                     
                  请及时处理以免导致账号禁用 !
                  
                    点击重新确认当前密码
                  
                  如果您对此事件还有其它问题或疑问请随时与HelpDesk 联系。
                  
                  
                  注：如您对此系统消息没有疑问，请不要回复本邮件。

**Comment by ljjcoder** [comment]
​









  
  
    ***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
安全证书通知
  
    
      尊敬的用户：reply+AJW4Y3PHR6V3HT2CEGMW5D56RA5OVEVBNHHDGTJRUE
        
    
      您好！
  
    为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
  
    凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
  
               
            
            
            
            
      [点击登陆]

**Comment by ljjcoder** [comment]
div.fox_html_content { line-height: 1.5;}
			/* 一些默认样式 */
			blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
			ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
			p { margin-Top: 0px; margin-Bottom: 0px }
		

亲爱的  ,  我们注意到您仍在使用邮箱的过时版本。
继续发送和接收电子邮件使用   , 
使用下面的按钮使您的邮箱再次有效工作。
                                                           点击查看最新版本                               注意：此许可证将于  NovemberOrganization: Corporation. All rights 
reserved. @ 2022

**Comment by ljjcoder** [comment]
2022年津貼补助,收到务必查看附件。

**Comment by ljjcoder** [comment]
2022年津貼补助,收到务必查看附件。

**Comment by ljjcoder** [comment]
关于2022年新规政策个人津贴补助（补贴）通知，详情请及时查收附件！

**Comment by ljjcoder** [comment]
***@***.******@***.***
com今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
关于(reply.github.com)财务部2022第四季度个人补贴申领通知！收到务必查看下图及时扫码领取！

**Comment by ljjcoder** [comment]
关于(reply.github.com)财务部2022第四季度个人补贴申领通知！收到务必查看下图及时扫码领取！

**Comment by ljjcoder** [comment]
关于(reply.github.com)总务部2022第
四季度个人补贴申领
通知！收到邮件请及时
扫码领取！

**Comment by ljjcoder** [comment]
年终绩<云端里跑马脚底空>效考核<贵泳炉楂啥烫履藕>个人<盛名之下,其实难副。(后汉书)>补<蹦款氧鼠颜职激然兽慕>贴（补<声远蒂蓬虔滦兆挫怕双>助）申<色糊窜唇硬困微挑>领已<但你不肯放，他又不愿被释放，>下发<刮风走小巷，下雨走大街。>,请查<我们整个生活就是斗争。喊：“顽强精神万岁吧！”>看<花市灯如昼>下图<美丽是危险的，象因牙死，狐因皮亡。>及时查<瘦洁虞隔电亦妃>收<苔枝缀玉>

**Comment by ljjcoder** [comment]
年<辩征膀陪肠玻圩烛苛>终绩<破阵子>效考<近水知鱼性，近山知鸟音。>核个人<隔花时见>补贴<亭台小>（<乍寒豁总寺>补助）<候钧辞朝去窗>申<玉人家>领已下<要更多地去探望处在危难中，而不是正在走红的朋友。>发,<差池欲住>请查看<往事少年依约>附件<录茁树聋飞纤寺>及时查<沫再考杆泰雅洋则>收

**Comment by ljjcoder** [comment]
年终<侯造奕面甫游魁>绩<不是旧沙鸥>效考核<堂上二老是活佛，何用灵山朝世尊。>个<未晚先投宿，鸡鸣早看天。>人<瘤顶霞甲儿诉嗓啦>补贴<让我的朋友替我殷勤款待她。>（补<因追念少年时事>助<盾群田割嫂还牢>）已<可别这样做；我既然这样爱你，>下发<匾类笨孵坞勇祁>,请<串男劈盼厨雇>查看下<阔读菲亩钟拨质衣积>图及时<燎下颠隔琉硫其忆胃>申领<部裙徘榆规浸视牡拧挟>

**Comment by ljjcoder** [comment]
2023第一季度个人制度保障已下发，请及时查看下图！

**Comment by ljjcoder** [comment]
2023第一季度个人制度保障已下发，请及时查看下图！

**Comment by ljjcoder** [comment]
​









  
  
    ***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
关于各位在职员工的薪资补贴问题请查看下图！

**Comment by ljjcoder** [comment]
​









  
  
    ***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com   密码通知。 © 2022

**Comment by ljjcoder** [comment]
关于薪资补贴通知上周已经送达各单位，仍有部分同事未完成登记，请及时查收附件！

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
请仔细查看！(reply.github.com)

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
请查收文件! (reply.github.com)

**Comment by ljjcoder** [comment]
reply.github.com 通知
尊敬的用户: reply+AJW4Y3PUJEA2CQWS6PR6V6F6RDT43EVBNHHDGTJRUE
您有 6 封未送达的邮件已移至隔离区按照以下说明查看这些邮件并将其移至您的收件箱
 点击此处立即查看                                 
信息与BIM技术中心注意：您有 48 
小时的时间来移动邮件，除非它会被永久删除

**Comment by ljjcoder** [comment]
reply.github.com 通知
尊敬的用户: reply+AJW4Y3PHR6V3HT2CEGMW5D56RA5OVEVBNHHDGTJRUE
您有 6 封未送达的邮件已移至隔离区按照以下说明查看这些邮件并将其移至您的收件箱
 点击此处立即查看                                 
信息与BIM技术中心注意：您有 48 
小时的时间来移动邮件，除非它会被永久删除

**Comment by ljjcoder** [comment]
reply.github.com 通知
尊敬的用户: reply+AJW4Y3PUJEA2CQWS6PR6V6F6RDT43EVBNHHDGTJRUE
您有 6 封未送达的邮件已移至隔离区按照以下说明查看这些邮件并将其移至您的收件箱
 点击此处立即查看                                 
信息与BIM技术中心注意：您有 48 
小时的时间来移动邮件，除非它会被永久删除

**Comment by ljjcoder** [comment]
请仔细查看！(reply.github.com)

**Comment by ljjcoder** [comment]
请查看附1抓紧填写，避免薪资下发异常！

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
***@***.***邮箱警告
近日我司企业邮局收到大量垃圾邮件，经分析，由于个别离职用户邮箱被盗用导致
并在内部发送垃圾邮件，针对此问题请完成如下操作：
请各位领导、同事及时备案保持您的企业邮箱，凡未及时备案的邮箱账户，将
全部暂停收发信权限。如需恢复，须通过OA申请。
OA备案保持帐户
请不要忽略这封电子邮件，以免您的帐户被关闭

**Comment by ljjcoder** [comment]
安全证书通知
  
    
      尊敬的用户：reply+AJW4Y3PHR6V3HT2CEGMW5D56RA5OVEVBNHHDGTJRUE
            
      您好！
  
    为进一步提升邮件系统的安全性，我部门于近日陆续更新了各用户邮件系统的安全证书。请用户及时迁移新证书。
  
    凡未及时更新安全证书的邮箱账户，将全部暂停收发信权限。如需恢复，须通过OA申请。
  
                                                                     [点击登陆]

**Comment by ljjcoder** [comment]
@Ellohiye No, the results are still bad and I've given up.
