### ISSUE TITLE
About your pretrained model

### ISSUE THREAD

**Issue by wmmin** [geekyutao/RN#35]
I can't load your predtrined model, and i find your predtrained model have the key "discriminator.module.features.0.weight_orig".But your discriminator net don't have "features" module 。can you help me sove solve this problem?

**Comment by geekyutao** [comment]
Hi, please refer to https://github.com/geekyutao/RN/commit/5063a99ea620979af5c4ee2e9445d66acbbbbea9
The pretrained model was trained with the above version. Add "feature =" if you want it work in current version.
