### ISSUE TITLE
How to test it for a single photo.

### ISSUE THREAD

**Issue by taratandel** [geekyutao/RN#37]
how can I test it on a single photo and its mask?

**Comment by geekyutao** [comment]
Hi, still need make file list (*.flist) first. You can use flist.py to achieve it. Then refer to the test command.

**Comment by geekyutao** [comment]
> how can I test it on a single photo and its mask?

Hi, still need make file list (*.flist) first. You can use flist.py to achieve it. Then refer to the test command.
