### ISSUE TITLE
Example Inputs and masks for evaluation

### ISSUE THREAD

**Issue by lyumingzhi** [geekyutao/RN#38]
Hi! Thank you very much for your excellent work. However, when i try  to go through the evaluation with Place2 with the provided pretrained model, the quality of the result is quite bad. Would you like to provide some examples that can work on the pretrained model or more concrete instructions?
![image](https://user-images.githubusercontent.com/43129252/177910896-06e415f0-848c-43e9-a939-a986d9d093c0.png)
![image](https://user-images.githubusercontent.com/43129252/177910925-9bf13e5b-402a-4aad-b131-c5daab36c37c.png)
![image](https://user-images.githubusercontent.com/43129252/177910950-86e04bf8-3265-448d-956c-7c78f848f605.png)

**Comment by geekyutao** [comment]
Test good from my side. Can you leave more context on your testing?

**Comment by beautylalaqiu** [comment]
Hello, thank you very much for your work. the picture I trained myself is normal, but the results of the test with the model I trained or the model you provided are not very good, can you provide the test parameters at that time?

**Comment by geekyutao** [comment]
> Hello, thank you very much for your work. the picture I trained myself is normal, but the results of the test with the model I trained or the model you provided are not very good, can you provide the test parameters at that time?

Hi, did you use the newest code?
