### ISSUE TITLE
Question about more regions (K>2)

### ISSUE THREAD

**Issue by c0ldheart** [geekyutao/RN#39]
Hi, in your work, the number of regions is 2（mask and others) and it performs very well. I'm wondering what form should a more number of regions look like, does every region still represent the occluded area in the image? And how to modify the code when K>2? 
Can you please tell me any experience or insight with this situation, any suggestions would be very helpful, thanks.

**Comment by geekyutao** [comment]
> Hi, in your work, the number of regions is 2（mask and others) and it performs very well. I'm wondering what form should a more number of regions look like, does every region still represent the occluded area in the image? And how to modify the code when K>2? Can you please tell me any experience or insight with this situation, any suggestions would be very helpful, thanks.

Hi, it should work when K>2. You should modify https://github.com/geekyutao/RN/blob/a66073744c582a922059e89153ddf656e43a02db/rn.py#L5

Try modifying binary labels by multiple labels.
