### ISSUE TITLE
Total instance number: 1

### ISSUE THREAD

**Issue by ZunxiaoXu** [geekyutao/RN#5]
hi,thanks for your work.
i have produce the train_image.flist/train_mask.flist/test_image.flist/test.mask.flist
but when i try training, it said "Total instance number: 1"as follow:
![image](https://user-images.githubusercontent.com/34836683/78096820-3a50eb80-740d-11ea-9e51-4950e40eb9e7.png)
and when i try the eval.py with your pretrainermodel is said "ValueError: num_samples should be a positive integer value, but got num_samples=0" as follow:
![image](https://user-images.githubusercontent.com/34836683/78097158-180b9d80-740e-11ea-91e0-8c1f297c722d.png)
both the problems seem that the data cannot to be loaded?hope your reply~

**Comment by geekyutao** [comment]
Hi, thanks for your attention to RN! 
I believe the problems you posted are caused by the I/O of the model. Specifically, the file lists you maked are not correct and then the pytorch dataset is maked wrongly. You can vim the flist and check if the image paths are correct.

**Comment by ZunxiaoXu** [comment]
i just chenked and unfortunately i donot know wheres the mistake
this is the path of dataset
![image](https://user-images.githubusercontent.com/34836683/78111700-a2182e00-742f-11ea-84ed-ff9c6ead1271.png)
and this is the flist
![image](https://user-images.githubusercontent.com/34836683/78111745-b0664a00-742f-11ea-94e3-b6420c224c65.png)

**Comment by geekyutao** [comment]
I've just ran the main.py and it worked well in my machine. Was your python command of training correct? 
![image](https://user-images.githubusercontent.com/30614660/78114888-8a8f7400-7434-11ea-96aa-be8dc89e136c.png)
 
I suggest you debug step-by-step. And make sure if the model has loaded data correctly first.

**Comment by ZunxiaoXu** [comment]
oh，thanks for your suggestion，i solved  the question above！but  there is a new problem as follow：
 
![image](https://user-images.githubusercontent.com/34836683/78229172-35219880-7502-11ea-8819-8290abfc85e5.png)
![image](https://user-images.githubusercontent.com/34836683/78229184-394db600-7502-11ea-84ba-cbcf1d49ab0b.png)
i  think  my dataset maybe bad？

**Comment by geekyutao** [comment]
It seems the "self.mask_data" is empty. Are you sure that the masks loading is correct ?

**Comment by ZunxiaoXu** [comment]
yes！you r right！it works after i modify the masks' path.but when i try the eval.py there are some problems as follow
![image](https://user-images.githubusercontent.com/34836683/78650839-0c2e4880-78f2-11ea-85fc-0019c01c65cd.png)
![image](https://user-images.githubusercontent.com/34836683/78650862-16504700-78f2-11ea-8718-c4a9d8726997.png)
some say it  is  because
![image](https://user-images.githubusercontent.com/34836683/78651123-7cd56500-78f2-11ea-918d-3a8a9d120f61.png)
but it did not work. i notice that you just update the code here to support cpu,but my trainning and evaling are all on the  centos,could you give some suggestions?

**Comment by geekyutao** [comment]
It's weird. It works well for my machine. Are you sure the codes you run are the newest?
![image](https://user-images.githubusercontent.com/30614660/78685114-e15ce800-7923-11ea-9354-dd03d2a5a29b.png)
