### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by wuzy2115** [geekyutao/RN#7]
Hi, @geekyutao thanks for your sharing. I've followed the discription on Readme.md, however when running eval.py it seems that the model loaded incorrectly, I used the pretrained model x_admin.cluster.localRN-0.8RN-Net_bs_14_epoch_3.pth and the error is showed as bellow:

`Traceback (most recent call last):
  File "/tmp/pycharm_project_13/eval.py", line 200, in <module>
    model.load_state_dict(pretained_model)
  File "/root/anaconda3/envs/pytorch040/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for InpaintingModel:
	Missing key(s) in state_dict: "discriminator.module.conv1.0.weight", "discriminator.module.features.0.weight", "discriminator.module.conv2.0.weight", "discriminator.module.conv3.0.weight", "discriminator.module.conv4.0.weight", "discriminator.module.conv5.0.weight". 
	Unexpected key(s) in state_dict: "discriminator.module.conv1.0.weight_v", "discriminator.module.features.0.weight_v", "discriminator.module.conv2.0.weight_v", "discriminator.module.conv3.0.weight_v", "discriminator.module.conv4.0.weight_v", "discriminator.module.conv5.0.weight_v". 
`

I have no idea where the problem is. Could you help me? Looking forward for your reply.

**Comment by geekyutao** [comment]
Hi, thanks for your attention on RN!
Did you use the newest codes of RN repo? It works okay in my machine.

**Comment by miaodd98** [comment]
Same problem, I try to set  model.load_state_dict(pretrained_model, False), but the result shows werid, there is no color inpainting. But with pretrained model everything goes well. I trained my model based on the pretrained model and got the same issue. Any suggestions? The training process goes very well and with a good visual result. Hope for your reply! Many thanks!

**Comment by juechen-zzz** [comment]
Same problem

**Comment by JasonLiTW** [comment]
I guess it's because the author trained the pretrained model with multiple gpu, you could modify [line 237 in main.py](https://github.com/geekyutao/RN/blob/a3cf1fccc08f22fcf4b336503a8853748720fd67/main.py#L237) from
`if opt.gpus > 1:`  to  `if opt.gpus >= 1:`, to use nn.DataParallel with a single gpu.

**Comment by juechen-zzz** [comment]
> I guess it's because the author trained the pretrained model with multiple gpu, you could modify [line 237 in main.py](https://github.com/geekyutao/RN/blob/a3cf1fccc08f22fcf4b336503a8853748720fd67/main.py#L237) from
> `if opt.gpus > 1:` to `if opt.gpus >= 1:`, to use nn.DataParallel with a single gpu.

Thanks, it works.
